# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
"""Aggregated knowpro interfaces for backwards compatibility."""

from __future__ import annotations

from .interfaces_core import *  # noqa: F401,F403
from .interfaces_indexes import *  # noqa: F401,F403
from .interfaces_search import *  # noqa: F401,F403
from .interfaces_serialization import *  # noqa: F401,F403
from .interfaces_storage import *  # noqa: F401,F403

__all__ = [
    "AddMessagesResult",
    "ConversationData",
    "ConversationDataWithIndexes",
    "ConversationMetadata",
    "ConversationThreadData",
    "DateRange",
    "Datetime",
    "DeletionInfo",
    "ICollection",
    "IConversation",
    "IConversationSecondaryIndexes",
    "IConversationThreads",
    "IKnowledgeExtractor",
    "IKnowledgeSource",
    "IMessage",
    "IMessageCollection",
    "IMessageMetadata",
    "IMessageTextIndex",
    "IPropertyToSemanticRefIndex",
    "IReadonlyCollection",
    "ISemanticRefCollection",
    "IStorageProvider",
    "ITermToRelatedTerms",
    "ITermToRelatedTermsFuzzy",
    "ITermToRelatedTermsIndex",
    "ITermToSemanticRefIndex",
    "ITimestampToTextRangeIndex",
    "IndexingStartPoints",
    "Knowledge",
    "KnowledgeData",
    "KnowledgePropertyName",
    "KnowledgeType",
    "MessageOrdinal",
    "MessageTextIndexData",
    "PropertySearchTerm",
    "ScoredMessageOrdinal",
    "ScoredSemanticRefOrdinal",
    "ScoredSemanticRefOrdinalData",
    "ScoredThreadOrdinal",
    "SearchSelectExpr",
    "SearchTerm",
    "SearchTermGroup",
    "SearchTermGroupTypes",
    "SemanticRef",
    "SemanticRefData",
    "SemanticRefOrdinal",
    "SemanticRefSearchResult",
    "Tag",
    "Term",
    "TermData",
    "TermToRelatedTermsData",
    "TermToSemanticRefIndexData",
    "TermToSemanticRefIndexItemData",
    "TermsToRelatedTermsDataItem",
    "TermsToRelatedTermsIndexData",
    "TextEmbeddingIndexData",
    "TextLocation",
    "TextLocationData",
    "TextRange",
    "TextRangeData",
    "TextToTextLocationIndexData",
    "Thread",
    "ThreadData",
    "ThreadDataItem",
    "ThreadOrdinal",
    "TimestampedTextRange",
    "Topic",
    "WhenFilter",
]
